# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bankScript' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PromiseKit', '6.13.1'
  pod 'Alamofire', '5.0.0-rc.2'
  pod 'AlamofireNetworkActivityLogger', '3.0'
  pod 'SwiftyJSON', '5.0.0'
  # Pods for bankScript

end
